# -*- coding: utf-8 -*-
"""trabalhin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVl97LY2pp7b1qkmzhLqcY65JLEx8tiA
"""

#!pip install ibm-watson
#!sudo apt install python3-pyaudio
#!pip install pyaudio

#import IPython
import os

while (1):
  
  print('Caso deseje converter um arquivo de áudio para arquivo de texto digite 1')
  print('Caso deseje converter um arquivo de áudio para texto no terminal digite 2')
  print('Caso deseje converter um arquivo de texto (.txt) para arquivo de áudio digite 3')
  print('Caso deseje digitar um texto e convertê-lo em arquivo de áudio digite 4')
  print('Caso deseje que sua fala seja convertida em texto, digite 5')
  print('Caso deseje digitar um texto seja convertido em fala, digite 6')
  print('Caso deseje sair da aplicação digite SAIR\n\n')

  opcao = input('Sua opção: ')

  if opcao == '1':
    os.system('cls' if os.name == 'nt' else 'clear')
    arq = 'scripts/watson_speech_file_to_text_file.py'
    exec(compile(open(arq).read(), arq, 'exec'))

  elif opcao == '2':
    os.system('cls' if os.name == 'nt' else 'clear')
    arq = 'scripts/watson_speech_file_to_text_terminal.py'
    exec(compile(open(arq).read(), arq, 'exec'))

  elif opcao == '3':
    os.system('cls' if os.name == 'nt' else 'clear')
    arq = 'scripts/watson_text_file_to_speech_file.py'
    exec(compile(open(arq).read(), arq, 'exec'))

  elif opcao == '4':
    os.system('cls' if os.name == 'nt' else 'clear')
    arq = 'scripts/watson_text_terminal_to_speech_file.py'
    exec(compile(open(arq).read(), arq, 'exec'))

  elif opcao == '5':
    os.system('cls' if os.name == 'nt' else 'clear')
    arq = 'scripts/watson_speech_to_text.py'
    exec(compile(open(arq).read(), arq, 'exec'))

  elif opcao == '6':
    os.system('cls' if os.name == 'nt' else 'clear')
    arq = 'scripts/watson_text_to_speech.py'
    exec(compile(open(arq).read(), arq, 'exec'))

  elif opcao == 'SAIR':
    break

  else:
    os.system('cls' if os.name == 'nt' else 'clear')
    print('\n\nPor favor informe uma opção válida\n\n')


