# -*- coding: utf-8 -*-
"""Watson_Speech_To_Text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HShAu-wjZRJuG2BsX_jEkUMuSUQt8W4J

# Watson Speech to Text

Neste notebook vamos usar a API Speech To Text do Watson. Com ela é possível realizar o reconhecimento de voz através de arquivos gravados.
"""

# !pip install ibm-watson
# !wget https://watson-developer-cloud.github.io/doc-tutorial-downloads/speech-to-text/reference/audio-file2.flac

from ibm_watson import SpeechToTextV1
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator
import json

"""Primeiramente, vamos criar o serviço passando nossos dados de autenticação:"""

authenticator = IAMAuthenticator(os.getenv('API_SPEECH_TO_TEXT'))
speech_to_text = SpeechToTextV1(
    authenticator=authenticator
)

"""Vamos utilizar o reconhecimento síncrono da API, utilizando o método recognize. Esse método possui diversos parâmetros. Primeiramente, vamos utilizar o método sem parâmetros:"""

oi = input('Por favor informe a localização do arquivo (file path): ')

with open(oi,'rb') as audio_file:
    speech_recognition_results = speech_to_text.recognize(
        audio=audio_file,
        model='pt-BR_Telephony',
        content_type='audio/'+oi.split('.')[-1]
    ).get_result()
# print(json.dumps(speech_recognition_results, indent=2))

texto = []
for i in range(len(speech_recognition_results['results'])):
  texto.append(speech_recognition_results['results'][i]['alternatives'][0]['transcript'])

import os
os.system('cls' if os.name == 'nt' else 'clear')

print()
print()

for linha in texto:
  print(linha)